- type: remove
  path: /instance_groups/name=broker-deploy/jobs/name=broker-deploy/properties/cf

- type: remove
  path: /instance_groups/name=broker-delete/jobs/name=broker-delete/properties/cf

- type: replace
  path: /instance_groups/name=broker-deploy/jobs/name=broker-deploy/consumes?/cf
  value:
    from: cf-admin-user
    deployment: cf

- type: replace
  path: /instance_groups/name=broker-delete/jobs/name=broker-delete/consumes?/cf
  value:
    from: cf-admin-user
    deployment: cf
